### ISSUE TITLE
:Esource opens a test

### ISSUE THREAD

**Issue by SevereOverfl0w** [tpope/vim-salve#10]
For some reason when I use `:Esource` it is opening the test files as well as creating them there by default. Any suggestions for what's going on?

**Comment by tpope** [comment]
It's derived from your class path. Got something weird going on there?

**Comment by SevereOverfl0w** [comment]
Not to my knowledge. Anything in particular I should check to make sure?

**Comment by tpope** [comment]
Do you override any paths at all in `project.clj`?

**Comment by SevereOverfl0w** [comment]
Checked both `~/.lein/profiles.clj` and `project.clj` of my most recent
project, nothing. (Have seen this on other projects too).

**Comment by tpope** [comment]
Oh, you want `:Emain` not `:Esource`. It's maven style naming. The only weird thing is that `:Esource` creates files at all.

**Comment by SevereOverfl0w** [comment]
Excellent. Thank you!
