### ISSUE TITLE
dev-resources > resources?

### ISSUE THREAD

**Issue by SevereOverfl0w** [tpope/vim-salve#11]
Is there a reason why `dev-resources` receives priority over `resources`?

Mostly as I'm a lein user, to me resources makes sense first. I'm probably misunderstanding again!

https://github.com/tpope/vim-salve/blob/a0dc869952a38285476ceba91787948c1759088b/plugin/salve.vim#L173

**Comment by tpope** [comment]
It's the same as lein's defaults.
