### ISSUE TITLE
Any way to keep the window inside of Vim?

### ISSUE THREAD

**Issue by mrmowgli** [tpope/vim-salve#13]
I use tmux and for the most part it is nice that the REPL is opening in the same term window, but for some reason tmux opens the repl in a full focused window.  I would love for this to open directly within VIM as a window, so I could hop around one space rather than have things move all over the place.  

Any ideas?

**Comment by tpope** [comment]
This will happen once https://github.com/tpope/vim-dispatch/pull/250 is complete.
