### ISSUE TITLE
Maybe only show "Create alternative file" prompt (for cljc) if the name.clj doesn't exist?

### ISSUE THREAD

**Issue by shmup** [tpope/vim-salve#16]
You might have a nice reason for handling it how you currently do. I'm new to Clojure and after seeing your plugin do this, had to learn what `cljc` even was. 

I just know, out of the box, lein makes the core.clj and test.core.clj and if you use `:A` to swap between test and implementation, it's going to trigger the create file prompt:

```
Create alternate file?
1 /home/jared/projects/golem/src/golem/generator.cljc
Type number and <Enter> or click with mouse (empty cancels):
```

And maybe that's fine. Close this and yell at me if so

**Comment by tpope** [comment]
I haven't used the plugin much since the CLJC stuff got added. If it's really prompting for *only* a `.cljc` file, and not also a `.clj` file, something is broken.
