### ISSUE TITLE
Opting out of classpath detection

### ISSUE THREAD

**Issue by daveyarwood** [tpope/vim-salve#18]
I use vim-salve solely for the feature where it auto-connects fireplace to the nREPL that I have running, which it is able to find because the nREPL spits its port into a `.nrepl-port` file in the current directory.

I prefer to start my REPLs manually, but I still find it really convenient that I don't need to do anything extra like go find the port of the REPL I started and then tell fireplace to connect to it. So that's really nice.

But lately, I've been finding the classpath detection (which can take several seconds or much longer, depending on the project) cumbersome, and I've been looking for a way to turn it off because I don't think I need it for my typical workflow.

What do you think about adding an option that would allow one to disable just the classpath detection part of vim-salve? Something like `g:disable_classpath_detection` or `g:disable_classpath_retrieval`?

I'd be happy to submit a PR if you're on-board with the idea.

**Comment by tpope** [comment]
It uses the class path to determine the location of your source code for navigation commands, etc. Disabling would require an alternate execution path with presumably hard coded defaults, which is not especially attractive.

**Comment by daveyarwood** [comment]
I've created a fork of vim-salve, [vim-diet-salve](https://github.com/daveyarwood/vim-diet-salve), which provides a small part of the functionality of vim-salve that doesn't rely on classpath detection or the projectionist features.

If you're reading this issue and your needs are similar to mine, give it a try! :slightly_smiling_face:
